### ISSUE TITLE
Error when I put url on input() ?

### ISSUE THREAD

**Issue by Bagusa4** [kkroening/ffmpeg-python#131]
Hello, I have some trouble when I use URL as a value in input function, I got this error, what I'm missing in here?

I would like to try to implement this original commend on FFmpeg
`ffmpeg -i "http://example.com/video_url.m3u8" -c copy -bsf:a aac_adtstoasc "output.mp4"`

does 'input.(source)' is equal as 'ffmpeg -i source' ?
but yeah when I try with this code:
```dofirst = ffmpeg.input(source)
dofirst = ffmpeg.output(dofirst, "master.mp4", **{'-bsf:a': 'aac_adtstoasc'})
ffmpeg.run(dofirst)
```

I get this stuff:
```Traceback (most recent call last):
  File "d:/Workspaces/Python/ytcd/ffmpegd.py", line 10, in <module>
    ffmpeg.run(dofirst)
  File "C:\Program Files\Python37\lib\site-packages\ffmpeg\_run.py", line 208, in run
    p = subprocess.Popen(args, stdin=stdin_stream, stdout=stdout_stream, stderr=stderr_stream)
  File "C:\Program Files\Python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by Bagusa4** [comment]
I try with `os.path` to get the relative path file each input and output, and clear. 
But I miss with  `-bsf:a` option in output, in the documentation I see `-b:v` for 'video_bitrate' and `-b:a` for 'audio_bitrate', but what is stand for `-bsf:a` is this 'audio_bitstream_filters' ? I try but it's doesn't work ?

`Unrecognized option 'audio_bitstream_filters'.
Error splitting the argument list: Option not found
Traceback (most recent call last):
  File "d:/Workspaces/Python/zdwl/zdwl.py", line 50, in <module>
    render(source=source)
  File "d:/Workspaces/Python/zdwl/zdwl.py", line 25, in render
    ffmpeg.run(dofirst, ffmpeg_exe)
  File "C:\Program Files\Python37\lib\site-packages\ffmpeg\_run.py", line 212, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)`

**Comment by gagantk** [comment]
Hello @Bagusa4, have you found any solution for this, please share.

**Comment by sailordiary** [comment]
Use `absf='aac_adtstoasc'`.

**Comment by bilabar** [comment]
Your code should have no dash in **bsf** parameter
```
dofirst = ffmpeg.output(dofirst, "master.mp4", **{'bsf:a': 'aac_adtstoasc'})
```

Look at  #136 
```
ffmpeg.input(new_filename).output(h264_stream, vcodec='copy', **{'bsf:v': h264_mp4toannexb'}).compile()
```
