### ISSUE TITLE
AttributeError: module 'ffmpeg' has no attribute 'input'

### ISSUE THREAD

**Issue by iamtahirkhan6** [kkroening/ffmpeg-python#174]
Traceback (most recent call last):
  File "/main/ffmpeg.py", line 1, in <module>
    import ffmpeg
  File "/main/ffmpeg.py", line 2, in <module>
    stream = ffmpeg.input('video.mp4')
AttributeError: module 'ffmpeg' has no attribute 'input'

**Comment by kkroening** [comment]
```pip install ffmpeg-python```
instead of
```pip install ffmpeg```

**Comment by muellermartin** [comment]
I had the same error, because `python-ffmpeg` was installed instead of `ffmpeg-python`. Therefore this can be considered as fixed.

**Comment by hldh214** [comment]
try another filename (don't use same name as your imported package)

**Comment by vinooo1095** [comment]
I'm guessing this happens if you've installed both, ffmpeg and ffmpeg-python.
uninstall both with:
`pip uninstall ffmpeg`
`pip uninstall ffmpeg-python`

and install ffmpeg-python again with :
`pip install ffmpeg-python`

This solved the problem in my system :)

**Comment by autofasurer** [comment]
Same problem, installed ffmpeg-python in virtual env for this particular project, uninstalled ffmpeg resulting in `WARNING: Skipping ffmpeg as it is not installed.`
Ffmpeg is still installed system wide though.

**Comment by thekillgfx** [comment]
```
(
        ffmpeg
        .input(video)
        .input(watermark)
        .output('test.mp4')
    )
>>> AttributeError: 'FilterableStream' object has no attribute 'input'
```

**Comment by shgninc** [comment]
I have same problem, install and uninstall the module multiple times.

but i forgot to install `ffmpeg` package.

**Comment by nlsdvl** [comment]
you will probably end up with that exact error if you do : 
`pip install python-ffmpeg`

instead of : 
`pip install ffmpeg-python`

at least, I did ...

**Comment by CharlesChen-ccc** [comment]
1. Make sure you had pip install ffmpeg-python
2. You should copy the ffmpeg.exe to you .py file work directory

**Comment by rupshac** [comment]
If I install ffmpeg + ffmpeg-python I see the same issue.

If I install only ffmpeg-python I see `"FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'`

**Comment by hobbitsyfeet** [comment]
If you're silly like me and create a file named `ffmpeg.py` to test things out, the first command you call is obviously `ffmpeg.input(...)`. Since you're re-defining ffmpeg it does not contain `ffmpeg.input`.

Therefore, `AttributeError: module 'ffmpeg' has no attribute 'input'`

The solution to this: Make sure your Python file isn't named ffmpeg.py

**Comment by 784682065** [comment]
> I'm guessing this happens if you've installed both, ffmpeg and ffmpeg-python.
> uninstall both with:
> `pip uninstall ffmpeg`
> `pip uninstall ffmpeg-python`
> 
> and install ffmpeg-python again with :
> `pip install ffmpeg-python`
> 
> This solved the problem in my system :)

thank you! If it wasn't for you, I would have been tortured to death.

**Comment by ShawKai666** [comment]
step 1：sudo apt install ffmpeg
step 2：pip install ffmpeg-python
step 3：pip uninstall ffmpeg

**Comment by KalininY** [comment]
> I'm guessing this happens if you've installed both, ffmpeg and ffmpeg-python. uninstall both with: `pip uninstall ffmpeg` `pip uninstall ffmpeg-python`
> 
> and install ffmpeg-python again with : `pip install ffmpeg-python`
> 
> This solved the problem in my system :)

Thank you very much!

**Comment by lixueqidaytoy** [comment]
> I'm guessing this happens if you've installed both, ffmpeg and ffmpeg-python. uninstall both with: `pip uninstall ffmpeg` `pip uninstall ffmpeg-python`
> 
> and install ffmpeg-python again with : `pip install ffmpeg-python`
> 
> This solved the problem in my system :)

Thanks, you help me a lot！

**Comment by StarfuryT** [comment]
I've tried all of the above solutions, I either get 
`"FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'`

or 

`AttributeError: module 'ffmpeg' has no attribute 'input'`

I've tried uninstall and re-installing in various different orders

**Comment by lixueqidaytoy** [comment]
> I've tried all of the above solutions, I either get `"FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'`
> 
> or
> 
> `AttributeError: module 'ffmpeg' has no attribute 'input'`
> 
> I've tried uninstall and re-installing in various different orders

I still have this problem in the Jupyter notebook, so I use vs code. 
   `AttributeError: module 'ffmpeg' has no attribute 'input'`  this can be solved, but I get new error.

`AttributeError: module 'ffmpeg' has no attribute 'run'`

if you get this, you just need to turn colored frames into video.

**Comment by StarfuryT** [comment]
I'm working in vscode and I still run into this issue.

**Comment by orange5E06** [comment]
May your interpreter  has no ffmpeg-python

**Comment by michalbartkowski** [comment]
Here is a possible fix to the error:
`AttributeError: module 'ffmpeg' has no attribute 'input'`

I found that the above error occurs only when my python script is named 'ffmpeg.py'

Renaming the script solves the above error in my case

**Comment by Portals72** [comment]
git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg

**Comment by swankwc** [comment]
So, I tried both uninstalls as follows,

Not much change from befefore...
(ytwhisper) Wesleys-MacBook-Air:whisper wesley$ pip uninstall ffmpeg
WARNING: Skipping ffmpeg as it is not installed.
(ytwhisper) Wesleys-MacBook-Air:whisper wesley$ pip uninstall ffmpeg-python
Found existing installation: ffmpeg-python 0.2.0
Uninstalling ffmpeg-python-0.2.0:
  Would remove:
    /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ffmpeg/*
    /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ffmpeg_python-0.2.0.dist-info/*
Proceed (Y/n)? y
  Successfully uninstalled ffmpeg-python-0.2.0
(ytwhisper) Wesleys-MacBook-Air:whisper wesley$ pip install ffmpeg-python
Collecting ffmpeg-python
  Using cached ffmpeg_python-0.2.0-py3-none-any.whl (25 kB)
Requirement already satisfied: future in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from ffmpeg-python) (0.18.2)
Installing collected packages: ffmpeg-python
Successfully installed ffmpeg-python-0.2.0
(ytwhisper) Wesleys-MacBook-Air:whisper wesley$ yt_whisper "https://www.youtube.com/watch?v=dQw4w9WgXcQ"yt_whisper "https://www.youtube.com/watch?v=dQw4w9WgXcQ" --model medium
Downloaded video "Rick Astley - Never Gonna Give You Up (Official Music Video)". Generating subtitles...
Downloaded video "Rick Astley - Never Gonna Give You Up (Official Music Video)". Generating subtitles...
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/whisper/audio.py", line 42, in load_audio
    ffmpeg.input(file, threads=0)
AttributeError: module 'ffmpeg' has no attribute 'input'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/yt_whisper", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/yt_whisper/cli.py", line 49, in main
    result = model.transcribe(audio_path, **args)
  File "/opt/homebrew/lib/python3.10/site-packages/whisper/transcribe.py", line 84, in transcribe
    mel = log_mel_spectrogram(audio)
  File "/opt/homebrew/lib/python3.10/site-packages/whisper/audio.py", line 111, in log_mel_spectrogram
    audio = load_audio(audio)
  File "/opt/homebrew/lib/python3.10/site-packages/whisper/audio.py", line 46, in load_audio
    except ffmpeg.Error as e:
AttributeError: module 'ffmpeg' has no attribute 'Error'
(ytwhisper) Wesleys-MacBook-Air:whisper wesley$

**Comment by ZZZsleepyheadZZZ** [comment]
I used `conda install -c conda-forge ffmpeg`, and it works. It turned out that ffmpeg installed by pip was of a too old version.

**Comment by 459737087** [comment]
### **pip install python-ffmpeg**
this is right

**Comment by dinuthomas** [comment]
Finally worked for me after doing this, 
1. pip uninstall ffmpeg-python
2. pip3 install ffmpeg-python

So try installing with pip3..

**Comment by Suvi-dha** [comment]
This worked for me:

1. uninstall ffmpeg-python 
2. pip install ffmpeg
3. pip install ffmpeg-python

**Comment by githmashwinkumar** [comment]
I have a very simple code - 
[
import whisper

model = whisper.load_model("base")
result = model.transcribe("D:\\Newfolder\\audio.mp3",fp16=False)
print(result["text"])
]

Have tried with "pip install python-ffmpeg" when it gave the error - "AttributeError: module 'ffmpeg' has no attribute 'Error'". Then tried with "pip install ffmpeg" and "pip install ffmpeg-python". Now it is throwing this error 
[ 
Traceback (most recent call last):
  File "D:\Newfolder\ds\ML\patrec\rec.py", line 4, in <module>
    result = model.transcribe("D:\\Newfolder\\audio.mp3",fp16=False)
  File "D:\Newfolder\ds\ML\patrec\venv\lib\site-packages\whisper\transcribe.py", line 121, in transcribe
    mel = log_mel_spectrogram(audio, padding=N_SAMPLES)
  File "D:\Newfolder\ds\ML\patrec\venv\lib\site-packages\whisper\audio.py", line 130, in log_mel_spectrogram
    audio = load_audio(audio)
  File "D:\Newfolder\ds\ML\patrec\venv\lib\site-packages\whisper\audio.py", line 46, in load_audio
    ffmpeg.input(file, threads=0)
  File "D:\Newfolder\ds\ML\patrec\venv\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "D:\Newfolder\ds\ML\patrec\venv\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\py39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\py39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
]
Can you please suggest a way-forward for addressing this?

**Comment by pardon-hnu** [comment]
> 
Thanks. you are my hero！It works

**Comment by githmashwinkumar** [comment]
> I have a very simple code - [ import whisper
> 
> model = whisper.load_model("base") result = model.transcribe("D:\Newfolder\audio.mp3",fp16=False) print(result["text"]) ]
> 
> Have tried with "pip install python-ffmpeg" when it gave the error - "AttributeError: module 'ffmpeg' has no attribute 'Error'". Then tried with "pip install ffmpeg" and "pip install ffmpeg-python". Now it is throwing this error [ Traceback (most recent call last): File "D:\Newfolder\ds\ML\patrec\rec.py", line 4, in result = model.transcribe("D:\Newfolder\audio.mp3",fp16=False) File "D:\Newfolder\ds\ML\patrec\venv\lib\site-packages\whisper\transcribe.py", line 121, in transcribe mel = log_mel_spectrogram(audio, padding=N_SAMPLES) File "D:\Newfolder\ds\ML\patrec\venv\lib\site-packages\whisper\audio.py", line 130, in log_mel_spectrogram audio = load_audio(audio) File "D:\Newfolder\ds\ML\patrec\venv\lib\site-packages\whisper\audio.py", line 46, in load_audio ffmpeg.input(file, threads=0) File "D:\Newfolder\ds\ML\patrec\venv\lib\site-packages\ffmpeg_run.py", line 313, in run process = run_async( File "D:\Newfolder\ds\ML\patrec\venv\lib\site-packages\ffmpeg_run.py", line 284, in run_async return subprocess.Popen( File "C:\py39\lib\subprocess.py", line 951, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "C:\py39\lib\subprocess.py", line 1420, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] The system cannot find the file specified ] Can you please suggest a way-forward for addressing this?

Installing System.Speech from nuget manager resolved this issue. Refered to [this link ](https://stackoverflow.com/questions/67711037/net-speechsynthesizer-throws-system-nullreferenceexception )

**Comment by raduking** [comment]
> I have a very simple code - [ import whisper
> 
> model = whisper.load_model("base") result = model.transcribe("D:\Newfolder\audio.mp3",fp16=False) print(result["text"]) ]
> 
> Have tried with "pip install python-ffmpeg" when it gave the error - "AttributeError: module 'ffmpeg' has no attribute 'Error'". Then tried with "pip install ffmpeg" and "pip install ffmpeg-python". Now it is throwing this error [ Traceback (most recent call last): File "D:\Newfolder\ds\ML\patrec\rec.py", line 4, in result = model.transcribe("D:\Newfolder\audio.mp3",fp16=False) File "D:\Newfolder\ds\ML\patrec\venv\lib\site-packages\whisper\transcribe.py", line 121, in transcribe mel = log_mel_spectrogram(audio, padding=N_SAMPLES) File "D:\Newfolder\ds\ML\patrec\venv\lib\site-packages\whisper\audio.py", line 130, in log_mel_spectrogram audio = load_audio(audio) File "D:\Newfolder\ds\ML\patrec\venv\lib\site-packages\whisper\audio.py", line 46, in load_audio ffmpeg.input(file, threads=0) File "D:\Newfolder\ds\ML\patrec\venv\lib\site-packages\ffmpeg_run.py", line 313, in run process = run_async( File "D:\Newfolder\ds\ML\patrec\venv\lib\site-packages\ffmpeg_run.py", line 284, in run_async return subprocess.Popen( File "C:\py39\lib\subprocess.py", line 951, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "C:\py39\lib\subprocess.py", line 1420, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] The system cannot find the file specified ] Can you please suggest a way-forward for addressing this?

As @vinooo1095 suggested already:

I'm guessing this happens if you've installed both, `ffmpeg` and `ffmpeg-python`.

Uninstall both with:

```bash
pip3 uninstall ffmpeg
pip3 uninstall ffmpeg-python
```

Then ONLY install `ffmpeg-python` again with:

```bash
pip3 install ffmpeg-python
```

**Comment by githmashwinkumar** [comment]
Thanks
Will try

**Comment by pablodz** [comment]
Still relevant

**Comment by jlmmunix** [comment]
sudo pip uninstall ffmpeg
sudo pip3 uninstall ffmpeg
sudo python -m pip uninstall ffmpeg
sudo python3 -m pip uninstall ffmpeg
sudo pip show ffmpeg
sudo pip show python-ffmpeg
sudo pip3 show ffmpeg
sudo pip3 show python-ffmpeg
sudo pip install ffmpeg-python
sudo pip3 install ffmpeg-python
sudo pip3 install ffmpeg-python
pip install ffmpeg-python --user
python3 -m pip install ffmpeg-python
pip install --ignore-installed ffmpeg-python
pip3 install --ignore-installed ffmpeg-python
python -m pip install --ignore-installed ffmpeg-python
python3 -m pip install --ignore-installed ffmpeg-python

**Comment by aronweiler** [comment]
So I ran into this issue today and came here to see a ton of people talking about solutions that don't work... the real solution here (besides making sure you have ffmpeg and ffmpeg-python installed) is to install ffmpeg manually so that you can access the executables.

Whisper is attempting to call ffmpeg by just invoking the "ffmpeg" command line.  No pathing is taken into account in these libraries, so you need to install ffmpeg AND make sure it's callable from your python application.

## Manual ffmpeg installation steps
1. Navigate to https://ffmpeg.org/download.html
2. Download (or clone and then build) the desired build of ffmpeg
3. Extract the files if you downloaded it
4. Add the bin path to your environment path

**Comment by L-a-n-s-c-e** [comment]
> I'm guessing this happens if you've installed both, ffmpeg and ffmpeg-python. uninstall both with: `pip uninstall ffmpeg` `pip uninstall ffmpeg-python`
> 
> and install ffmpeg-python again with : `pip install ffmpeg-python`
> 
> This solved the problem in my system :)

Thanks I was bout to go crazy restarting and reinstalling ffmpeg over and over.

**Comment by alvinkimata** [comment]
> I'm guessing this happens if you've installed both, ffmpeg and ffmpeg-python. uninstall both with: `pip uninstall ffmpeg` `pip uninstall ffmpeg-python`
> 
> and install ffmpeg-python again with : `pip install ffmpeg-python`
> 
> This solved the problem in my system :)

This worked for me. Thanks a lot!

**Comment by desaiankitb** [comment]
For me none of the above solutions worked. However, the following did worked. I was using this in ipynb you can modify the commands as per your environments. Don't change the sequence. 

```! apt-get --purge remove libav-tools
! apt-get --purge autoremove
! yes | pip uninstall ffmpeg
! yes | pip uninstall ffmpeg-python
! yes | apt-get -y install ffmpeg
! yes | conda install -c conda-forge ffmpeg-python
! yes | pip install ffmpeg-python

**Comment by 101is5** [comment]
This is how it worked for me:
* install ffmpeg through ```choco``` or ```scoop```, as mentioned [here](https://github.com/openai/whisper) (Apparently, it's different than through ```pip```);
* install ffmpeg-python through ```python -m pip install ffmpeg-python```, or run ```pip install -U openai-whisper```, which installs ffmpeg-python.

Before that, I had come across 3 types of errors when swaping between ffmpeg and ffmpeg-python pip instalations:

* with ffmpeg or both installed: 
```Exception has occurred: AttributeError
module 'ffmpeg' has no attribute 'Error'
AttributeError: module 'ffmpeg' has no attribute 'input'

During handling of the above exception, another exception occurred:

  File "C:\Users\[me]\Documents\programacao\testwhisper\wsp.py", line 5, in <module>
    text = model.transcribe("audio.mp3")
AttributeError: module 'ffmpeg' has no attribute 'Error'
```

* with ffmpeg-python only:
```
Exception has occurred: FileNotFoundError
[WinError 2] O sistema não pode encontrar o arquivo especificado
  File "C:\Users\[me]\Documents\programacao\testwhisper\wsp.py", line 5, in <module>
    text = model.transcribe("audio.mp3")
FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado
```
By the way, ```pip install``` hasn't worked for me in a while. It's been only ```python -m pip install ...```, otherwise I get a "not accessed by Pylance" error and, if I try running the script, I get:
```Exception has occurred: ModuleNotFoundError
No module named 'ffmpeg'
  File "C:\Users\[me]\Documents\programacao\testwhisper\wsp.py", line 2, in <module>
    import whisper
ModuleNotFoundError: No module named 'ffmpeg'
```

**Comment by luoshuiyang** [comment]
> step 1：sudo apt install ffmpeg step 2：pip install ffmpeg-python step 3：pip uninstall ffmpeg

I solved the problem using this method，thank you very much.Even solved other problem with this solution.

**Comment by SiNaPsEr0x** [comment]
> > I'm guessing this happens if you've installed both, ffmpeg and ffmpeg-python.
> > uninstall both with:
> > `pip uninstall ffmpeg`
> > `pip uninstall ffmpeg-python`
> > and install ffmpeg-python again with :
> > `pip install ffmpeg-python`
> > This solved the problem in my system :)
> 
> thank you! If it wasn't for you, I would have been tortured to death.

thanks for solution on docker its ok!

**Comment by LeviArckman** [comment]
> I'm guessing this happens if you've installed both, ffmpeg and ffmpeg-python. uninstall both with: `pip uninstall ffmpeg` `pip uninstall ffmpeg-python`
> 
> and install ffmpeg-python again with : `pip install ffmpeg-python`
> 
> This solved the problem in my system :)

doesn't work

**Comment by Xoro399** [comment]
Reinstall ffmpeg

**Comment by moluuser** [comment]
```bash
pip install ffmpeg
pip uninstall ffmpeg -y
pip install python-ffmpeg
pip uninstall python-ffmpeg -y
pip install ffmpeg-python
pip uninstall ffmpeg-python -y
```

Then
```bash
pip install ffmpeg-python
```

**Comment by YamatoDX** [comment]
I had the same problem because **both** `ffmpeg-python` and `ffmpeg` were installed on my system.
So, I did
`pip uninstall ffmpeg-python`
`pip uninstall ffmpeg`

Then I installed **only** the ffmpeg-python
`pip install ffmpeg-python`
