### ISSUE TITLE
Pattern type 'glob' was selected but globbing is not supported by this libavformat build

### ISSUE THREAD

**Issue by rankuptuts** [kkroening/ffmpeg-python#180]
When I try this,

```
import ffmpeg

(
    ffmpeg
    .input('C:/Users/myUser/PycharmProjects/abvabvabv/downloads/rsdfsdfe/images/*.jpg', pattern_type='glob', framerate=25)
    .output('movie.mp4')
    .run()
)

```

Then, I get this error, any clues ?

> ffmpeg version N-73010-gbb3703a Copyright (c) 2000-2015 the FFmpeg developers
>   built with gcc 4.9.2 (GCC)
>   configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --enable-decklink --enable-zlib
>   libavutil      54. 27.100 / 54. 27.100
>   libavcodec     56. 41.100 / 56. 41.100
>   libavformat    56. 37.100 / 56. 37.100
>   libavdevice    56.  4.100 / 56.  4.100
>   libavfilter     5. 17.100 /  5. 17.100
>   libswscale      3.  1.101 /  3.  1.101
>   libswresample   1.  2.100 /  1.  2.100
>   libpostproc    53.  3.100 / 53.  3.100
> [image2 @ 0000000007126c40] Pattern type 'glob' was selected but globbing is not supported by this libavformat build
> C:/Users/myUser/PycharmProjects/abvabvabv/downloads/rsdfsdfe/images/*.jpg: Function not implemented
> Traceback (most recent call last):
>   File "C:/Users/myUser/PycharmProjects/abvabvabv/python-ffmepg-demo.py", line 6, in <module>
>     .output('movie.mp4')
>   File "C:\Users\myUser\PycharmProjects\abvabvabv\venv\lib\site-packages\ffmpeg\_run.py", line 305, in run
>     raise Error('ffmpeg', out, err)
> ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
> 
> Process finished with exit code 1

**Comment by nebukadhezer** [comment]
Windows does not support globbing as glob.h is not available for windows, maybe there is a way to do the globbing via python first and then feed each frame to ffmpeg ? 
We typically consolidate the sequence so there are no gaps in the numbers frame.1001.jpg, frame.1002.jpg....
Would love to have this feature on windows too, osx and linux is no problem...

**Comment by nebukadhezer** [comment]
https://trac.ffmpeg.org/wiki/Slideshow
maybe the concat demuxer or the pipe is a way to make this possible on windows.
