### ISSUE TITLE
ModuleNotFoundError: No module named 'past'

### ISSUE THREAD

**Issue by jmmartinezbr** [kkroening/ffmpeg-python#228]
I have the following issue when the code under it.

I`ve installed using 'pip install ffmpeg' and 'pip install ffmpeg-python' and both present the same error.

-----
"C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\python.exe" "C:/Users/Admin/Documents/Midia_flow_ff/Main.py"
Traceback (most recent call last):
  File "C:/Users/Admin/Documents/Midia_flow_ff/Main.py", line 2, in <module>
    import ffmpeg
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ffmpeg\__init__.py", line 2, in <module>
    from . import nodes
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ffmpeg\nodes.py", line 3, in <module>
    from past.builtins import basestring
ModuleNotFoundError: No module named 'past'

----
`import ffmpeg
print('Encoding Starded')
stream = ffmpeg.input('input.MOV')
stream = ffmpeg.hflip(stream)
stream = ffmpeg.output(stream, 'output.MOV')
ffmpeg.run(stream)
print('Encoding Ended')
`

**Comment by ChristopherBanas** [comment]
Any fix?

**Comment by mattia-lecci** [comment]
try `pip install future`
source: https://pypi.org/project/past/
