### ISSUE TITLE
error making video from sequence of images

### ISSUE THREAD

**Issue by sanromd** [kkroening/ffmpeg-python#255]
HI @kkroening 

I am creating a set of videos from a high speed FLIR camera. I tried using the code in the examples, but I am getting an unknown error when running the code. I tried running the ffmpeg code directly from the terminal and it works, so I am not sure what I am doing wrong here. Any help will be much appreciated.

Thank you

```python
import ffmpeg, os

process = (
    ffmpeg
    .input('"' + os.path.join(figpath,'*.png')+'"', pattern_type='glob', framerate=f_rate)
    .output(outfile, crf=25, preset='medium', pix_fmt='yuv420p', vcodec='libx264')
)

print(process.get_args())

#['-framerate', '349', '-pattern_type', 'glob', '-i', '"/media/sanromd/data/lab/data/laser_experiments/_unsorted/irdata/laser-experiments/perforation/un_007/test_02/figs/*.png"', '-crf', '25', '-pix_fmt', 'yuv420p', '-preset', 'medium', '-vcodec', 'libx264', '/media/sanromd/data/lab/data/laser_experiments/_unsorted/irdata/laser-experiments/perforation/un_007/test_02/vids/un_007_1.mp4']

process.run(capture_stderr=True, capture_stdout=True)
```

error:

---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-66-5c15ec1bac16> in <module>
----> 1 process.run(capture_stderr=True, capture_stdout=True)

/sandbox/opt/share/anaconda/lib/python3.7/site-packages/ffmpeg/_run.py in run(stream_spec, cmd, capture_stdout, capture_stderr, input, quiet, overwrite_output)
    323     retcode = process.poll()
    324     if retcode:
--> 325         raise Error('ffmpeg', out, err)
    326     return out, err
    327 

Error: ffmpeg error (see stderr output for detail)

**Comment by Rom1Linux** [comment]
Hello, i have an error too for the output with png files 

spec: windows 10 / python 2.7

my code: 
```
import ffmpeg
(
    ffmpeg
    .input('P:\\test_anim_iso_spectral\\*.png', f='image2', pattern_type='glob', framerate=25)
    .output('C:\\Users\\myname\\Desktop\\movie.mp4', pix_fmt='yuv420p')
    .run()
)
```

here: C:\\Users\\myname\\Desktop\\movie.mp4' is not found
```
C:\Users\myname\Desktop\convert_ffmpeg.py
Traceback (most recent call last):
  File "C:\Users\myname\Desktop\convert_ffmpeg.py", line 5, in <module>
    .output('C:\\Users\\myname\\Desktop\\movie.mp4', pix_fmt='yuv420p')
  File "C:\Python27\lib\site-packages\ffmpeg\_run.py", line 320, in run
    overwrite_output=overwrite_output,
  File "C:\Python27\lib\site-packages\ffmpeg\_run.py", line 285, in run_async
    args, stdin=stdin_stream, stdout=stdout_stream, stderr=stderr_stream
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] Le fichier spÚcifiÚ est introuvable
```
