### ISSUE TITLE
How to run -var_stream_map and -map options?

### ISSUE THREAD

**Issue by abhyuditjain** [kkroening/ffmpeg-python#294]
Hi,

I have an array of bitrates like this: `['320k', '128k', '64k', '32k']` and I would like to run the following for the above case:

```
ffmpeg -y -i song.mp3 -flags +cgop -g 30 \
-map a:0 -map a:0 -map a:0 -map a:0 \
-c:a aac -b:a:0 320k \
-c:a aac -b:a:1 128k \
-c:a aac -b:a:2 64k \
-c:a aac -b:a:3 32k \
-var_stream_map "a:0,name:320k a:1,name:128k a:2,name:64k a:3,name:32k" -f hls -hls_time 10 -hls_list_size 0 -hls_segment_filename "%v/segment%03d.ts" -master_pl_name "master.m3u8"  "%v/index.m3u8"
```

How would I go about using this:

I tried:
```
bitrates = ['320k', '128k', '64k', '32k']
out_files = ['%%v/%s.m3u8' % out_file_prefix]
out_flags = {
    'y': '',
    'f': 'hls',
    'c:a': 'aac',
    'hls_list_size': 0,
    'hls_time': 10,
    'master_pl_name': 'master.m3u8',
    'hls_segment_filename': '%s/%%v/%s_segment-%%03d.ts' % (out_path, out_file_prefix),
    'master_pl_name': 'master.m3u8'
}
map_arg_string = []
bitrate_arg_string = []
var_stream_map = []
for i, v in enumerate(bitrates):
    map_arg_string.append('-map a:0')
    bitrate_arg_string.append('-b:a:%d %s' % (i, v))
    var_stream_map.append('a:%d,name:%s' % (i, v))
out_flags[' '.join(map_arg_string)] = ''
out_flags[' '.join(bitrate_arg_string)] = ''
out_flags['var_stream_map'] = ' '.join(var_stream_map)
out = ffmpeg.output('song.mp3', self.out_files[0], **out_flags[0])
ffmpeg.run(out, overwrite_output=True)
```

The output for ffmpeg.get_args():
`['-i', 'song.mp3', '-f', 'hls', '--b:a:0 320k -b:a:1 128k', '', '--map a:0 -map a:0', '', '-c:a', 'aac', '-hls_list_size', '0', '-hls_segment_filename', '/%v/song_segment-%03d.ts', '-hls_time', '10', '-master_pl_name', 'master.m3u8', '-var_stream_map', 'a:0,name:320k a:1,name:128k', '-y', '', '/%v/song.m3u8']`

Error:

```
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.8)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.1_1 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/adoptopenjdk-13.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-13.jdk/Contents/Home/include/darwin -fno-stack-check' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Unrecognized option '-b:a:0 320k -b:a:1 128k'.
Error splitting the argument list: Option not found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/b0214344/Code/Wynk/minions/serverless-transcoder/common/transcoder.py", line 35, in transcode
    ffmpeg.run(out, cmd=self.command, overwrite_output=True)
  File "/Users/b0214344/Envs/ets/lib/python3.7/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
```

Also, the ordering is not maintained (understandable as it's a dict). Is there any way we can run the above command?

**Comment by BramFr** [comment]
i`ll think this is your problem
```
Unrecognized option '-b:a:0 320k -b:a:1 128k'.
```
You must place a , between every options. Look below output below.
```
['-i', 'song.mp3', '-f', 'hls', '--b:a:0 320k', '--b:a:1 128k', '', '--map a:0 -map a:0', '', '-c:a', 'aac', '-hls_list_size', '0', '-hls_segment_filename', '/%v/song_segment-%03d.ts', '-hls_time', '10', '-master_pl_name', 'master.m3u8', '-var_stream_map', 'a:0,name:320k a:1,name:128k', '-y', '', '/%v/song.m3u8']
```
But at this point. You have duplicate map options. That's not allowed.
 
I have the same problem with this:
```
TypeError: output() got multiple values for keyword argument 'map'
```
I like to use something like this dict output:
```
{'video_bitrate': 7599999, 'maxrate': 7599999, 'bufsize': 22799997, 'acodec': 'aac', 'sn': None, 'audio_bitrate': '384k', 'ac': 2, 'tune': 'zerolatency', 'movflags': 'faststart', 'loglevel': 'warning', 'map:0', map': '0:m:language:eng', 'stats': None}
```

**Comment by BramFr** [comment]
possible solution #420
