### ISSUE TITLE
Combining an image and audio to make a video

### ISSUE THREAD

**Issue by mysistersbrother** [kkroening/ffmpeg-python#414]
So I was writing a program where I can combine audio and an image into one video (the length of the audio)
This is the code:
`input_still = ffmpeg.input(picture)
    input_audio = ffmpeg.input("audio.mp3")

    (
        ffmpeg
        .concat(input_still, input_audio, v=1, a=1)
        .output("output.mp4")
        .run(overwrite_output=True)
    )`

I get presented with this large error:
`ffmpeg version git-2020-05-04-5767a2e Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200328
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 43.100 / 56. 43.100
  libavcodec     58. 82.100 / 58. 82.100
  libavformat    58. 42.102 / 58. 42.102
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 80.100 /  7. 80.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, image2, from 'pictures\image0 (4).jpg':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 5648 kb/s
    Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 357x476 [SAR 1:1 DAR 3:4], 25 tbr, 25 tbn, 25 tbc
[mp3 @ 0000000000576800] Estimating duration from bitrate, this may be inaccurate
Input #1, mp3, from 'audio.mp3':
  Duration: 00:00:02.57, start: 0.000000, bitrate: 32 kb/s
    Stream #1:0: Audio: mp3, 24000 Hz, mono, fltp, 32 kb/s
Stream mapping:
  Stream #0:0 (mjpeg) -> concat:in0:v0
  Stream #1:0 (mp3float) -> concat:in0:a0
  concat:out:a0 -> Stream #0:0 (aac)
  concat:out:v0 -> Stream #0:1 (libx264)
Press [q] to stop, [?] for help
[libx264 @ 0000000002d8b940] width not divisible by 2 (357x476)
Error initializing output stream 0:1 -- Error while opening encoder for output stream #0:1 - maybe incorrect parameters such as bit_rate, rate, width or height
[aac @ 0000000000570e00] Qavg: nan
Conversion failed!
Traceback (most recent call last):
  File "C:/Users/User/PycharmProjects/insultEmails/insultEmailer.py", line 44, in <module>
    ffmpeg
  File "C:\Users\User\.virtualenvs\insultEmails\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)`
What do I do?

**Comment by ljwobker** [comment]
The smoking gun is here:
`[libx264 @ 0000000002d8b940] width not divisible by 2 (357x476) Error`
The libx264 encoder requires that the frame size be divisible by two, which yours is not.  If you resize your inputs to meet this criteria you should be able to move forward...

**Comment by mysistersbrother** [comment]
> The smoking gun is here:
> `[libx264 @ 0000000002d8b940] width not divisible by 2 (357x476) Error`
> The libx264 encoder requires that the frame size be divisible by two, which yours is not. If you resize your inputs to meet this criteria you should be able to move forward...

Thank you this helped! However there is another problem unfortunately. I rescaled all the images I was using and made sure the WIDTH and HEIGHT were even numbers (divisible by 2). Prior to this when I tried to open the _output.mp4_, windows just gave me an error dialog saying there is something wrong with the file or something like that. Now it opens successfully and I see the image it used for a split second but then the video ends instantly. I put the video file into a editing software and I saw that the audio and video were there, the audio went for how long as it was supposed to but the video part (which is the image) only went for one frame, so this makes me come to the conclusion that windows media player just stops the video when it is had run out of video and doesn't care if the audio continues. FFMPEG didn't actually spit out a Traceback error but it did spit out a whole bunch of red text again. 
`ffmpeg version git-2020-05-04-5767a2e Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200328
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 43.100 / 56. 43.100
  libavcodec     58. 82.100 / 58. 82.100
  libavformat    58. 42.102 / 58. 42.102
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 80.100 /  7. 80.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, image2, from 'pictures\new8.jpg':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 10969 kb/s
    Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 640x360, 25 tbr, 25 tbn, 25 tbc
[mp3 @ 0000000000576880] Estimating duration from bitrate, this may be inaccurate
Input #1, mp3, from 'audio.mp3':
  Duration: 00:00:02.95, start: 0.000000, bitrate: 32 kb/s
    Stream #1:0: Audio: mp3, 24000 Hz, mono, fltp, 32 kb/s
Stream mapping:
  Stream #0:0 (mjpeg) -> concat:in0:v0
  Stream #1:0 (mp3float) -> concat:in0:a0
  concat:out:a0 -> Stream #0:0 (aac)
  concat:out:v0 -> Stream #0:1 (libx264)
Press [q] to stop, [?] for help
[libx264 @ 0000000002e1b2c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0000000002e1b2c0] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0000000002e1b2c0] 264 - core 159 - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'output.mp4':
  Metadata:
    encoder         : Lavf58.42.102
    Stream #0:0: Audio: aac (LC) (mp4a / 0x6134706D), 24000 Hz, mono, fltp, 69 kb/s (default)
    Metadata:
      encoder         : Lavc58.82.100 aac
    Stream #0:1: Video: h264 (libx264) (avc1 / 0x31637661), yuvj420p(pc), 640x360, q=-1--1, 25 fps, 12800 tbn, 25 tbc (default)
    Metadata:
      encoder         : Lavc58.82.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=    1 fps=0.0 q=28.0 Lsize=      51kB time=00:00:02.98 bitrate= 140.2kbits/s speed=87.8x    
video:24kB audio:25kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 3.263164%
[aac @ 000000000058b600] Qavg: 7605.532
[libx264 @ 0000000002e1b2c0] frame I:1     Avg QP:30.61  size: 24088
[libx264 @ 0000000002e1b2c0] mb I  I16..4:  2.1% 84.5% 13.5%
[libx264 @ 0000000002e1b2c0] 8x8 transform intra:84.5%
[libx264 @ 0000000002e1b2c0] coded y,uvDC,uvAC intra: 88.0% 63.8% 36.1%
[libx264 @ 0000000002e1b2c0] i16 v,h,dc,p: 26% 21%  5% 47%
[libx264 @ 0000000002e1b2c0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 20% 25% 20%  3%  5%  6% 12%  4%  7%
[libx264 @ 0000000002e1b2c0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 51% 20%  8%  2%  4%  4%  6%  3%  3%
[libx264 @ 0000000002e1b2c0] i8c dc,h,v,p: 55% 23% 19%  3%
[libx264 @ 0000000002e1b2c0] kb/s:4817.60`

Maybe the settings I am using in my code are incorrect? This is my first time using the FFMPEG library and I don't know how to use it properly. I am still using the code I showed in the original cost by the way. 

Thank you so much for the help once again!
