### ISSUE TITLE
Concat for varying length

### ISSUE THREAD

**Issue by Owez** [kkroening/ffmpeg-python#468]
I'd like to concatinate a non-fixed amount of audio-video streams together. I currently have a list like so of paths corrosponding to `v1, a1, v2, a2, v3, a3` etc which may be varied in length:

```python
x  = ["1.mp4", "1.mp3", "2.mp4", "2.mp3"]
```

And i'd like to concatinate these. I was thinking something like:

```python
ffmpeg.concat(*x, v=1, a=1).output("output.mp4").run()
```

But it apparently only accepts a `ffmpeg.nodes.FilterableStream` as seen in this traceback:

```none
Traceback (most recent call last):
  File "redata.py", line 180, in <module>
    ffmpeg.concat(*videostream, v=1, a=1).output("playlist.mp4").run()
  File "/home/owen/.local/share/virtualenvs/redata-c2MOZ56k/lib/python3.8/site-packages/ffmpeg/_filters.py", line 399, in concat
    return FilterNode(streams, concat.__name__, kwargs=kwargs, max_inputs=None).stream()
  File "/home/owen/.local/share/virtualenvs/redata-c2MOZ56k/lib/python3.8/site-packages/ffmpeg/nodes.py", line 266, in __init__
    super(FilterNode, self).__init__(
  File "/home/owen/.local/share/virtualenvs/redata-c2MOZ56k/lib/python3.8/site-packages/ffmpeg/nodes.py", line 202, in __init__
    self.__check_input_types(stream_map, incoming_stream_types)
  File "/home/owen/.local/share/virtualenvs/redata-c2MOZ56k/lib/python3.8/site-packages/ffmpeg/nodes.py", line 172, in __check_input_types
    raise TypeError(
TypeError: Expected incoming stream(s) to be of one of the following types: ffmpeg.nodes.FilterableStream; got <class 'str'>
```

Any help would be appreciated, I cant seem to get it to work!

**Comment by Owez** [comment]
Made an error by not using `ffmpeg.input(path)`, whoops! Closing

**Comment by OnlyOneMoreHour** [comment]
Kann you please spezifiy what you dind wrong and how to fixed it?

**Comment by payalrajguru** [comment]
stream = ffmpeg.input('C:/My_Work_Quixy/yolov5_final/yolov5_env/runs/detect/exp/Crossroads.mp4')

stream = ffmpeg.output(input,'C:/My_Work_Quixy/yolov5_final/yolov5_env/data/video_outputs/out.mp3')

ffmpeg.run(stream)

this is my code everything is correct still showing error , TypeError: Expected incoming stream(s) to be of one of the following types: ffmpeg.nodes.FilterableStream; got <class 'builtin_function_or_method'>
