### ISSUE TITLE
Cannot convert a video that has been outputted from a numpy array back to a numpy array.

### ISSUE THREAD

**Issue by RashiqAzhan** [kkroening/ffmpeg-python#512]
I have video `test.mkv` that I have converted a NumPy array `video` and then back to a video `text_2.mkv`. Not I can't convert this new video back to a NumPy array. The code is below.

```
import hashlib
import ffmpeg
import numpy as np

file_name = 'test.mkv'

probe = ffmpeg.probe(file_name)
video_stream = next((stream for stream in probe['streams'] if stream['codec_type'] == 'video'), None)
width = int(video_stream['width'])
height = int(video_stream['height'])

out, error = (
    ffmpeg
        .input(file_name, threads=120)
        .output("pipe:", format='rawvideo')
        .run(capture_stdout=True)
)

video = (
    np
        .frombuffer(out, np.uint8)
        .reshape([-1, height, width, 3])
)

video_buffer = (
    np.ndarray
        .flatten(video)
        .tobytes()
)

# Convert NumPy array to video
process = (
    ffmpeg
        .input('pipe:', format='rawvideo', s='{}x{}'.format(width, height))
        .output("test_2.mkv", r=30)
        .overwrite_output()
        .run_async(pipe_stdin=True)
)
process.communicate(input=video_buffer)

out_2, error = (
    ffmpeg
        .input("test_2.mkv", threads=40)
        .output("pipe:", format='rawvideo')
        .run(capture_stdout=True)
)

video_2 = (
    np
        .frombuffer(out_2, np.uint8)
        .reshape([-1, height, width, 3])
)

print(out==out_2) # False. Why don't they match?

print(np.array_equal(video, video_2)) # This must equal to True

print(hashlib.sha256(bytes(video_2)).digest()) # These hashes must be the same
print(hashlib.sha256(bytes(video)).digest())
```

Terminal Output:
```
Traceback (most recent call last):
  File "...\.venv\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-dd88ca422995>", line 1, in <module>
    runfile('.../main2.py', args=['pypy'], wdir='...')
  File "...\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "...\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File ".../main2.py", line 113, in <module>
    .reshape([-1, height, width, 3])
ValueError: cannot reshape array of size 997764480 into shape (1080,608,3)
```

I would like to be able to convert it to a NumPy array and have both the output be the same.

**Comment by DoGunKIM93** [comment]
Hello! 
Did you solve this problem?
I encounterd same problem.
