### ISSUE TITLE
Trying to convert Video into Images

### ISSUE THREAD

**Issue by IamExperimenting** [kkroening/ffmpeg-python#569]
I am trying to convert video into images using the below code, unfortunately, I am receiving FileNotFoundError. Wondering where should I create the folder. Also, I haven't mentioned the folder path there. 

Code:
import ffmpeg
import os
try:
    (ffmpeg.input('MyMovie49.mov')
          .filter('fps', fps=2)
          .output('images/%d.png', 
                  video_bitrate='5000k',
                  s='64x64',
                  sws_flags='bilinear',
                  start_number=0)
          .run(capture_stdout=True, capture_stderr=True))
except ffmpeg.Error as e:
    print('stdout:', e.stdout.decode('utf8'))
    print('stderr:', e.stderr.decode('utf8'))
Error:
Traceback (most recent call last):
  File "FFMPEG.py", line 11, in <module>
    .run(capture_stdout=True, capture_stderr=True))
  File "/home/falconheavy/miniconda3/envs/TFDev/lib/python3.7/site-packages/ffmpeg/_run.py", line 320, in run
    overwrite_output=overwrite_output,
  File "/home/falconheavy/miniconda3/envs/TFDev/lib/python3.7/site-packages/ffmpeg/_run.py", line 285, in run_async
    args, stdin=stdin_stream, stdout=stdout_stream, stderr=stderr_stream
  File "/home/falconheavy/miniconda3/envs/TFDev/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/falconheavy/miniconda3/envs/TFDev/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg': 'ffmpeg'

**Comment by Spider-ant** [comment]
I'm just trying to get an example to run and getting the same.

FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

I'm sorry to see there have been no replies to this.

**Comment by Spider-ant** [comment]
Ok... found some info here https://github.com/kkroening/ffmpeg-python/issues/251
