### ISSUE TITLE
ffprobe error (see stderr output for detail)

### ISSUE THREAD

**Issue by lingjivoo** [kkroening/ffmpeg-python#706]
import ffmpeg
from ffmpeg import probe

file = "/data1/luocheng/1.mp4"
media_file = file
print(ffmpeg.probe(media_file)["streams"])

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    print(ffmpeg.probe(media_file)["streams"])
  File "/data1/luocheng/anaconda3/envs/work36_cu11/lib/python3.6/site-packages/ffmpeg/_probe.py", line 23, in probe
    raise Error('ffprobe', out, err)
ffmpeg._run.Error: ffprobe error (see stderr output for detail)

**Comment by fgeisser2** [comment]
My error sounds pretty similar:
```
[libopenh264 @ 0x55d48a3df7c0] Incorrect library version loaded
    Last message repeated 1 times
[libopenh264 @ 0x55d48a733980] Incorrect library version loaded
    Last message repeated 1 times
[mp4 @ 0x55d48a717680] dimensions not set
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:2 -- 

Traceback (most recent call last):
  File ".../dl.py", line 85, in <module>
    ffmpeg.run(output)
  File "~/.local/lib/python3.10/site-packages/ffmpeg/_run.py", line 337, in run
    raise Error('ffmpeg', out, err)

```

I am on Fedora 36. Did a few updates, since I last used it (libopenh264 got updated from 2.2.0 to 2.3.0, ffmpeg is still 4.4.2). Working fine in Ubuntu.
