### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by mikezang** [kkroening/ffmpeg-python#792]
When I run `pip install ffmpeg-python` in win10, I got error as below, what can I do?

> Collecting ffmpeg-python
  Using cached ffmpeg_python-0.2.0-py3-none-any.whl (25 kB)
Collecting future (from ffmpeg-python)
  Using cached future-0.18.3.tar.gz (840 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\w802479\AppData\Local\Temp\pip-install-s0wpwnlq\future_53877af6f82d472b8267f9b494d54eff\setup.py", line 86, in <module>
          import src.future
      ModuleNotFoundError: No module named 'src'
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Amorano** [comment]
Did you find resolution for this? I have the exact same error on a pip install.
