### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 139 column 6 (char 4763)

### ISSUE THREAD

**Issue by BlazarBruce** [kkroening/ffmpeg-python#847]
Traceback (most recent call last):
  File "E:\test.py", line 30, in <module>
    streams = ffmpeg.probe(file_path)['streams']
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\konwledge_explore\venv\Lib\site-packages\ffmpeg_python-0.2.0-py3.12.egg\ffmpeg\_probe.py", line 27, in probe
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
  json.decoder.JSONDecodeError: Expecting ',' delimiter: line 139 column 6 (char 4763)
  
 I want to get the video file stream information, but unstable throw this error, I throw the error of the video file out of the execution, and normal again。

**Comment by BlazarBruce** [comment]
The format of file_path is
F:\\格式\\追风者（2024）\\追风者.War.of.Faith.S01E27.2024.2160p.WEB-DL.DDP5.1.H265-Pure@HDSWEB.mkv
