### ISSUE TITLE
Fails on unicode filename on windows

### ISSUE THREAD

**Issue by Abdullah2993** [kkroening/ffmpeg-python#90]
unable to process filenames with Unicode characters in them like `é`

```
Traceback (most recent call last):
  File "C:\Users\abdullah\src\python\ffmpeg-dir-conv\bulkc.py", line 46, in <module>
    main()
  File "C:\Users\abdullah\src\python\ffmpeg-dir-conv\bulkc.py", line 33, in main
    s = ffmpeg.input(f)
  File "C:\Python27\lib\site-packages\ffmpeg\_ffmpeg.py", line 27, in input
    return InputNode(input.__name__, kwargs=kwargs).stream()
  File "C:\Python27\lib\site-packages\ffmpeg\nodes.py", line 173, in __init__
    kwargs=kwargs
  File "C:\Python27\lib\site-packages\ffmpeg\nodes.py", line 124, in __init__
    super(Node, self).__init__(incoming_edge_map, name, args, kwargs)
  File "C:\Python27\lib\site-packages\ffmpeg\dag.py", line 119, in __init__
    self.__hash = self.__get_hash()
  File "C:\Python27\lib\site-packages\ffmpeg\dag.py", line 111, in __get_hash
    hashes = self.__upstream_hashes + [self.__inner_hash]
  File "C:\Python27\lib\site-packages\ffmpeg\dag.py", line 108, in __inner_hash
    return get_hash(props)
  File "C:\Python27\lib\site-packages\ffmpeg\_utils.py", line 63, in get_hash
    repr_ = _recursive_repr(item).encode('utf-8')
  File "C:\Python27\lib\site-packages\ffmpeg\_utils.py", line 55, in _recursive_repr
    kv_pairs = ['{}: {}'.format(_recursive_repr(k), _recursive_repr(item[k])) for k in sorted(item)]
  File "C:\Python27\lib\site-packages\ffmpeg\_utils.py", line 55, in _recursive_repr
    kv_pairs = ['{}: {}'.format(_recursive_repr(k), _recursive_repr(item[k])) for k in sorted(item)]
  File "C:\Python27\lib\site-packages\ffmpeg\_utils.py", line 51, in _recursive_repr
    result = str(item)
  File "C:\Python27\lib\site-packages\future\types\newstr.py", line 102, in __new__
    return super(newstr, cls).__new__(cls, value)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 21: ordinal not in range(128)
```

**Comment by Abdullah2993** [comment]
for anyone else having this issue on windows should use

```
import sys 
reload(sys)  
sys.setdefaultencoding('Cp1252')
```
 in their scripits

**Comment by kkroening** [comment]
Hmm, I'm not sure what to do about this. It'd be helpful if others on Windows could chime in.

Thanks for the bypass snippet. I'll leave this open in case someone else runs into the same issue.

**Comment by MaLeLabTs** [comment]
I have the same problem with Python 2.7, I have video file names with 'à' letter, exception is:

`'ascii' codec can't decode byte 0xc3 in position 63: ordinal not in range(128)'`

Pyhton 2.7 unicode support is tricky I remind I wrote workarounds in the past for this. I keep searching for a solution.

**Comment by ftarlao** [comment]
I have the same problem with Python 2.7 in Linux, I have video file names with 'à' letter, exception is:

'ascii' codec can't decode byte 0xc3 in position 63: ordinal not in range(128)'

Pyhton 2.7 unicode support is tricky I remind I wrote workarounds in the past for this. I keep searching for a solution.

**Update (found solution):**
Python 2.7 does not manage strings very well, sometimes the base str type is "inconsistent", the data inside does not fit the encoding. The only solution is to decode/reencode the string by forcing things.
In my case this old code of mine works (in Linux):

            if sys.version_info[0] < 3:
                #only Python 2
                filename = filename.decode('utf8')
 
You have to 'clean' the strings first than passing to `python-ffmpeg`.
This is common problem with Python 2.7 and considering input sanitization into python-ffmpeg is not a wrong idea. Please use my code in case.

**Comment by the-vindicar** [comment]
The issue is still present. Monkeypatch method mentioned by abdullah2993 appears to be Python 2 specific and is not present in Python 3.

This behaviour comes from `subprocess` module as I was unable to bypass the error by calling `ffmpeg` executable myself. 
If I call some built-in windows executable (for example, `attrib`) instead of `ffmpeg`, it accepts the filename with no problem. Similarly, I'm unable to access non-ascii named files when callign `ffmpeg` from command line.

By taking a look at how the filename is mangled by incorrect transcoding, I can assume that `ffmpeg` receives filenames encoded in UTF-8, but outputs (and opens?) them as if encoded in a single-byte encoding, in my case CP866 (DOS Cyrillic codepage). 
I'm not entirely sure how I can use this information to bypass the bug, as I can't encode filenames myself as non-utf-8 encoded bytes. 
If I attempt to use a single string, or `os.fsencode()` parts of the argument list, `ffmpeg` is called, but fails to find the file.
If I attempt to put a non `fsencode`d bytes into the argument list, it produces decoding error as `subprocess` passes the list through `os.fsdecode` to get rid of bytes objects.
If I attempt to use a single `fsencode`d bytes object intead of an argument list, I end up with "executable not found" error coming from WinAPI.

It is a bit of disappointment, as I hoped this module would be some kind of binding to `ffmpeg` _library_ rather than executable...
